### ISSUE TITLE
Calculate Emax(t/2,t)

### ISSUE THREAD

**Issue by mbaityje** [matthewcarbone/hdspin#20]
Calculate Emax(t/2,t), as in https://iopscience.iop.org/article/10.1088/1742-5468/ab38bf/meta . Look at fig.3 in the reference.
The minimum over t of this function can be used to calculate the threshold. But:

- This is only the result of a heuristic argument, and never verified in the REM because of too small system sizes
- This method might be influenced by whether we are in the entropic or in the energetic phase 

It is not important to have this quantity at every time. Logarithmically spaced times are enough.

**Comment by matthewcarbone** [comment]
Should be on `master` now. Once I confirm it's working I'll close.

**Comment by matthewcarbone** [comment]
@mbaityje just to confirm, we're basically reproducing this for the _Gaussian_ REM at $T=0.75$:

<img width="571" alt="image" src="https://github.com/matthewcarbone/hdspin/assets/26401020/c1a8cd23-7962-48ba-be10-7db530a47873">
